project_id          = "audioclassification-279617"
region              = "us-central1"
zone                = "us-central1-a"
location            = "us-central1-a"
credentials_file    = "..\\credentials_file.json"